// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Rmrs.Infrastructure.Persistence;

#nullable disable

namespace Rmrs.Infrastructure.Persistence.Migrations;

[DbContext(typeof(RmrsDbContext))]
[Migration("20240101000000_InitialSchema")]
partial class InitialSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // This is a placeholder designer file.
        // In a real scenario, EF Core tools would generate
        // the full model snapshot here.
    }
}
