// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Rmrs.Infrastructure.Persistence;

#nullable disable

namespace Rmrs.Infrastructure.Persistence.Migrations;

[DbContext(typeof(RmrsDbContext))]
partial class RmrsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // This is a placeholder model snapshot.
        // Run 'dotnet ef migrations add' to generate the real snapshot
        // once a SQL Server instance is available.
    }
}
